# PAGE-SPECIFIC CONTRIBUTORS
# ==========================
# QUICK NOTE:
#   1. Your contributor data shall be supplied in the .Data.Hestia.Creators/
#      directory. Here, you only list them out using their data filename as the
#      Key for this page and update their contribution.
#   2. Example entries:
#        [[Contributors]]
#        Key = 'Holloway'
#
#        [Contributors.Contribution]
#        Creation = true
#        Contact = true
#        Artwork = false
#        Knowledge = true
#        Editor = true
#        Developer = false
#        Maintainer = false
#        Producer = false
#        Provider = false
#        Publisher = false
#        Funder = false
#        Sponsor = false
#
#        [[Contributors]]
#        Key = 'CoryGalyna'
#
#        [Contributors.Contribution]
#        Creation = false
#        Contact = false
#        Artwork = false
#        Knowledge = false
#        Editor = true
#        Developer = false
#        Maintainer = false
#        Producer = false
#        Provider = false
#        Publisher = false
#        Funder = true
#        Sponsor = false
#
#        ...
[[Contributors]]
Key = 'HollowayKeanHo'

[Contributors.Contribution]
Developer = true
Creation = true
Artwork = true




[[Contributors]]
Key = 'MaxRahubovskiy'

[Contributors.Contribution]
Artwork = true




[[Contributors]]
Key = 'Sibertius'

[Contributors.Contribution]
Knowledge = true




[[Contributors]]
Key = 'CoryGalyna'

[Contributors.Contribution]
Maintainer = true
Editor = true




[[Contributors]]
Key = 'ZORALab'

[Contributors.Contribution]
Contact = true
Producer = true
Provider = true
Publisher = true
Funder = true
